const { readFileSync } = require('fs');
const { resolve } = require('path');

// Load .env file into env vars for all processes
const envFile = resolve(__dirname, '.env');
const envVars = {};
try {
  readFileSync(envFile, 'utf8').split('\n').forEach(line => {
    line = line.trim();
    if (!line || line.startsWith('#')) return;
    const eq = line.indexOf('=');
    if (eq === -1) return;
    envVars[line.slice(0, eq)] = line.slice(eq + 1);
  });
} catch {}

module.exports = {
  apps: [
    {
      name: 'web',
      script: 'node',
      args: '--import tsx/esm --import ./src/lib/instrument.ts src/web/index.tsx',
      cwd: '/home/opennews/open-news',
      instances: 1, autorestart: true, watch: false,
      max_memory_restart: '512M',
      env: { ...envVars, OTEL_SERVICE_NAME: 'open-news-web', DB_POOL_MAX: '8' },
      error_file: '/var/log/opennews/web-error.log',
      out_file: '/var/log/opennews/web-out.log',
    },
    {
      name: 'firehose',
      script: 'node',
      args: '--import tsx/esm --import ./src/lib/instrument.ts src/firehose/index.ts',
      cwd: '/home/opennews/open-news',
      instances: 1, autorestart: true, watch: false,
      max_memory_restart: '256M',
      env: { ...envVars, OTEL_SERVICE_NAME: 'open-news-firehose' },
      error_file: '/var/log/opennews/firehose-error.log',
      out_file: '/var/log/opennews/firehose-out.log',
      exp_backoff_restart_delay: 100,
    },
    {
      name: 'worker',
      script: 'node',
      args: '--import tsx/esm --import ./src/lib/instrument.ts src/worker/index.ts',
      cwd: '/home/opennews/open-news',
      instances: 1, autorestart: true, watch: false,
      max_memory_restart: '384M',
      env: { ...envVars, OTEL_SERVICE_NAME: 'open-news-worker' },
      error_file: '/var/log/opennews/worker-error.log',
      out_file: '/var/log/opennews/worker-out.log',
    },
    {
      name: 'track-web',
      script: 'node',
      args: '--import tsx/esm src/track/web.ts',
      cwd: '/home/opennews/open-news',
      instances: 1, autorestart: true, watch: false,
      max_memory_restart: '256M',
      env: { ...envVars, TRACK_PORT: '4200' },
      error_file: '/var/log/opennews/track-web-error.log',
      out_file: '/var/log/opennews/track-web-out.log',
    },
    {
      name: 'track-worker',
      script: 'node',
      args: '--import tsx/esm src/track/worker.ts',
      cwd: '/home/opennews/open-news',
      instances: 1, autorestart: true, watch: false,
      max_memory_restart: '256M',
      env: envVars,
      error_file: '/var/log/opennews/track-worker-error.log',
      out_file: '/var/log/opennews/track-worker-out.log',
    },
    {
      name: 'feeds-web',
      script: 'node',
      args: '--import tsx/esm src/feeds/web.ts',
      cwd: '/home/opennews/open-news',
      instances: 1, autorestart: true, watch: false,
      max_memory_restart: '256M',
      env: { ...envVars, DB_POOL_MAX: '8' },
      error_file: '/var/log/opennews/feeds-web-error.log',
      out_file: '/var/log/opennews/feeds-web-out.log',
    },
    {
      name: 'weblog',
      script: 'node',
      args: '--import tsx/esm src/weblog/index.ts',
      cwd: '/home/opennews/open-news',
      instances: 1, autorestart: true, watch: false,
      max_memory_restart: '256M',
      env: { ...envVars, WEBLOG_PORT: '4400' },
      error_file: '/var/log/opennews/weblog-error.log',
      out_file: '/var/log/opennews/weblog-out.log',
    },
    {
      name: 'longform',
      script: 'node',
      args: '--import tsx/esm src/longform/index.tsx',
      cwd: '/home/opennews/open-news',
      instances: 1, autorestart: true, watch: false,
      max_memory_restart: '256M',
      env: { ...envVars, LONGFORM_PORT: '4500', LONGFORM_DOMAIN: 'longform.social', DB_POOL_MAX: '8' },
      error_file: '/var/log/opennews/longform-error.log',
      out_file: '/var/log/opennews/longform-out.log',
    },
    {
      name: 'centipedia',
      script: 'node',
      args: '--import tsx/esm --import ./src/lib/instrument.ts src/centipedia/index.tsx',
      cwd: '/home/opennews/open-news',
      instances: 1, autorestart: true, watch: false,
      max_memory_restart: '256M',
      env: { ...envVars, CENTIPEDIA_PORT: '4600', CENTIPEDIA_DOMAIN: 'centipedia.org', OTEL_SERVICE_NAME: 'centipedia', DB_POOL_MAX: '8' },
      error_file: '/var/log/opennews/centipedia-error.log',
      out_file: '/var/log/opennews/centipedia-out.log',
    },
    {
      name: 'nearby',
      script: 'node',
      args: '--import tsx/esm src/nearby/index.tsx',
      cwd: '/home/opennews/open-news',
      instances: 1, autorestart: true, watch: false,
      max_memory_restart: '256M',
      env: { ...envVars, NEARBY_PORT: '4700', NEARBY_DOMAIN: 'nearby.at', DB_POOL_MAX: '8' },
      error_file: '/var/log/opennews/nearby-error.log',
      out_file: '/var/log/opennews/nearby-out.log',
    },
    {
      name: 'blogs',
      script: 'node',
      args: '--import tsx/esm src/blogs/index.tsx',
      cwd: '/home/opennews/open-news',
      instances: 1, autorestart: true, watch: false,
      max_memory_restart: '256M',
      env: { ...envVars, BLOGS_PORT: '4800', BLOGS_DOMAIN: 'blogs.social', DB_POOL_MAX: '8' },
      error_file: '/var/log/opennews/blogs-error.log',
      out_file: '/var/log/opennews/blogs-out.log',
    },
    {
      name: 'fatlink',
      script: 'node',
      args: '--import tsx/esm src/fatlink/index.ts',
      cwd: '/home/opennews/open-news',
      instances: 1, autorestart: true, watch: false,
      max_memory_restart: '256M',
      env: { ...envVars, FATLINK_PORT: '4900', FATLINK_DOMAIN: 'fat.link' },
      error_file: '/var/log/opennews/fatlink-error.log',
      out_file: '/var/log/opennews/fatlink-out.log',
    },
    {
      name: 'localnews',
      script: 'node',
      args: '--import tsx/esm src/localnews/index.ts',
      cwd: '/home/opennews/open-news',
      instances: 1, autorestart: true, watch: false,
      max_memory_restart: '256M',
      env: { ...envVars, LOCALNEWS_PORT: '5000', LOCALNEWS_DOMAIN: 'stamfordtimes.com' },
      error_file: '/var/log/opennews/localnews-error.log',
      out_file: '/var/log/opennews/localnews-out.log',
    },
    {
      name: 'media-worker',
      script: 'node',
      args: '--import tsx/esm src/media/worker.ts',
      cwd: '/home/opennews/open-news',
      instances: 1, autorestart: true, watch: false,
      max_memory_restart: '512M',
      env: envVars,
      error_file: '/var/log/opennews/media-worker-error.log',
      out_file: '/var/log/opennews/media-worker-out.log',
    },
    {
      name: 'media-gpu',
      script: '/home/opennews/open-news/src/media/gpu/.venv/bin/uvicorn',
      args: 'media_service:app --host 0.0.0.0 --port 8101',
      cwd: '/home/opennews/open-news/src/media/gpu',
      interpreter: '/home/opennews/open-news/src/media/gpu/.venv/bin/python3',
      interpreter_args: '-u',
      instances: 1, autorestart: true, watch: false,
      max_memory_restart: '8G',
      env: envVars,
      error_file: '/var/log/opennews/media-gpu-error.log',
      out_file: '/var/log/opennews/media-gpu-out.log',
    },
    {
      name: 'snip',
      script: 'node',
      args: '--import tsx/esm src/snip/index.tsx',
      cwd: '/home/opennews/open-news',
      instances: 1, autorestart: true, watch: false,
      max_memory_restart: '256M',
      env: { ...envVars, SNIP_PORT: '5100' },
      error_file: '/var/log/opennews/snip-error.log',
      out_file: '/var/log/opennews/snip-out.log',
    },
    {
      name: 'bucket',
      script: 'node',
      args: '--import tsx/esm src/bucket/index.tsx',
      cwd: '/home/opennews/open-news',
      instances: 1, autorestart: true, watch: false,
      max_memory_restart: '256M',
      env: { ...envVars, BUCKET_PORT: '5200', BUCKET_DOMAIN: 'bucket.social', BUCKET_BASE_URL: 'https://bucket.social' },
      error_file: '/var/log/opennews/bucket-error.log',
      out_file: '/var/log/opennews/bucket-out.log',
    },
  ],
};

