module.exports = {
  apps: [
    {
      name: 'web',
      script: 'node',
      args: '--import tsx/esm src/web/index.tsx',
      cwd: '/home/opennews/open-news',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env_file: '.env',
      error_file: '/var/log/opennews/web-error.log',
      out_file: '/var/log/opennews/web-out.log',
    },
    {
      name: 'firehose',
      script: 'node',
      args: '--import tsx/esm src/firehose/index.ts',
      cwd: '/home/opennews/open-news',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      env_file: '.env',
      error_file: '/var/log/opennews/firehose-error.log',
      out_file: '/var/log/opennews/firehose-out.log',
      exp_backoff_restart_delay: 100,
    },
    {
      name: 'worker',
      script: 'node',
      args: '--import tsx/esm src/worker/index.ts',
      cwd: '/home/opennews/open-news',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '384M',
      env_file: '.env',
      error_file: '/var/log/opennews/worker-error.log',
      out_file: '/var/log/opennews/worker-out.log',
    },
  ],
};
