CREATE TABLE IF NOT EXISTS post_mapping (
  id SERIAL PRIMARY KEY,
  uri TEXT NOT NULL UNIQUE,
  handle TEXT NOT NULL,
  original_content TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS media_mapping (
  url TEXT PRIMARY KEY,
  cid TEXT NOT NULL,
  mime TEXT NOT NULL,
  size INTEGER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
